name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: okc0202/nahc
          stage: main
          yaml: >
            name: nahc-petgang

            app: web

            options:
              nodeversion: "22"
              spa: true
              buildenv:
                - name: VITE_KAKAO_APP_KEY
                  value: ${{ secrets.VITE_KAKAO_APP_KEY }}
                - name: VITE_X_NAHC_TOKEN
                  value: ${{ secrets.VITE_X_NAHC_TOKEN }}
                - name: VITE_LLM_BACKEND_URL
                  value: ${{ secrets.VITE_LLM_BACKEND_URL }}
                - name: VITE_DEPLOY_BACKEND_URL
                  value: ${{ secrets.VITE_DEPLOY_BACKEND_URL }} 
                - name: VITE_TOUR_APP_KEY
                  value: ${{ secrets.VITE_TOUR_APP_KEY }}  
                - name: VITE_TOUR_BASE_URL
                  value: ${{ secrets.VITE_TOUR_BASE_URL }}
              rewrites: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: react-vite